// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATScjDkGmnNXNVc3-CWgvqgS1g1vp6LSk',
    appId: '1:972571775632:web:22ffc148da0f5c61f7be15',
    messagingSenderId: '972571775632',
    projectId: 'myanimal-50405',
    authDomain: 'myanimal-50405.firebaseapp.com',
    storageBucket: 'myanimal-50405.firebasestorage.app',
    measurementId: 'G-9YE5KH4CKY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW5IH0J2FbKbRWMtrI8VEL_o5WR5znsmU',
    appId: '1:972571775632:android:9f02f2f480a3d8a2f7be15',
    messagingSenderId: '972571775632',
    projectId: 'myanimal-50405',
    storageBucket: 'myanimal-50405.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgyQp9mop9AbDDIRiIWnLupDzEs9_1HRc',
    appId: '1:972571775632:ios:4cc4e069183f0f12f7be15',
    messagingSenderId: '972571775632',
    projectId: 'myanimal-50405',
    storageBucket: 'myanimal-50405.firebasestorage.app',
    iosClientId: '972571775632-s6h37s9ob36od9vjcr0tne9ek4rgrhj4.apps.googleusercontent.com',
    iosBundleId: 'com.example.myAnimal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgyQp9mop9AbDDIRiIWnLupDzEs9_1HRc',
    appId: '1:972571775632:ios:4cc4e069183f0f12f7be15',
    messagingSenderId: '972571775632',
    projectId: 'myanimal-50405',
    storageBucket: 'myanimal-50405.firebasestorage.app',
    iosClientId: '972571775632-s6h37s9ob36od9vjcr0tne9ek4rgrhj4.apps.googleusercontent.com',
    iosBundleId: 'com.example.myAnimal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATScjDkGmnNXNVc3-CWgvqgS1g1vp6LSk',
    appId: '1:972571775632:web:19c1a746c0a8404ff7be15',
    messagingSenderId: '972571775632',
    projectId: 'myanimal-50405',
    authDomain: 'myanimal-50405.firebaseapp.com',
    storageBucket: 'myanimal-50405.firebasestorage.app',
    measurementId: 'G-WV3G9W0HNE',
  );
}
